apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
spec:
  dependencies:
    - name: github-event
      eventSourceName: github-eventsource
      eventName: github
  triggers:
    - template:
        name: github-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            inline: |
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-ci-
              spec:
                entrypoint: helloworld
                templates:
                  - name: helloworld
                    container:
                      image: alpine
                      command: [echo]
                      args: ["Hello, World!"]
      policy:
        k8s:
          allow: true
