apiVersion: v1
kind: Service
metadata:
  name: myflask-service
spec:
  ports:
    - name: 5000-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: myflask
  sessionAffinity: None
  type: ClusterIP