apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
  labels:
    app: myflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
        - name: myflask
          image: myflask:34fd7bea72ab062aceed5efbb35149986861fed6
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: minikube-hostvolume
            mountPath: /tmp
      volumes:
      - name: minikube-hostvolume
        persistentVolumeClaim:
          claimName: minikuber-hostvolume-claim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: myflask-service
spec:
  ports:
    - name: 5000-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: myflask
  sessionAffinity: None
  type: ClusterIP

