apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-hostvolume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ryan/miniHDD/Learning/kubernetes/k8s-test/minikube-host-path
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minikuber-hostvolume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: minikube-hostvolume